file = _{SOI ~ program ~ EOI}
program = { sexpr* }
sexpr = {"(" ~ (sexpr | atom)* ~ ")"}
atom = _{ symbol | string }
symbol = @{ (ASCII_ALPHA | "-" | "." | "+" | "_") ~ (ASCII_ALPHANUMERIC | "-" | "." | "+" | "/" | "_")* }
string = ${ "\"" ~ inner ~ "\"" }
inner = @{ char* }
char = {
    !("\"" | "\\") ~ ANY
    | "\\" ~ ("\"" | "\\" | "/" | "f" | "n" | "r")
}
WHITESPACE = _{ " " | "\n" | "\r"}
COMMENT = _{ ";" ~ (!NEWLINE ~ ANY)* ~ NEWLINE}